### ISSUE TITLE
PubMed parser doesn't get YEAR anymore

### ISSUE THREAD

**Issue by marco-brandizi** [Rothamsted/ondex-knet-builder#13]
The text mining module doesn't pick YEAR anymore from the PubMed XML. I've investigated it and I found that the current XML is like:

```xml
<MedlineCitation Status="PubMed-not-MEDLINE" Owner="NLM">
    <PMID Version="1">29545818</PMID>
    <DateRevised>
        <Year>2018</Year>
        <Month>03</Month>
        <Day>18</Day>
    </DateRevised>
    <Article PubModel="Electronic-eCollection">
        <Journal>
            <ISSN IssnType="Print">1664-462X</ISSN>
            <JournalIssue CitedMedium="Print">
                <Volume>9</Volume>
                <PubDate>
                    <Year>2018</Year>
                </PubDate>
            </JournalIssue>
            ...
        </Journal>
         ...
        <ArticleDate DateType="Electronic">
            <Year>2018</Year>
            <Month>03</Month>
            <Day>01</Day>
        </ArticleDate>
        ...
```

The parser doesn't work because it looks for `MedlineCitation/Article/CreationDate/*`, which is not there. My understanding is that it should catch `MedlineCitation/Article/ArticleDate/Year/*` instead.

Please confirm me it's like that. The XML I've checked is the same as #12 .

**Comment by KeywanHP** [comment]
Yep makes sense to catch `MedlineCitation/Article/ArticleDate/Year/*` instead.

**Comment by marco-brandizi** [comment]
Doesn't work yet:

> Thanks Marco. Most publication concepts have a YEAR again… But strangely it’s still missing in some concepts, e.g.
> 
> https://www.ncbi.nlm.nih.gov/pubmed/24882934?report=xml&format=text
> https://www.ncbi.nlm.nih.gov/pubmed/11706173?report=xml&format=text
> https://www.ncbi.nlm.nih.gov/pubmed/27228605?report=xml&format=text
> 
> Keywan
>

**Comment by marco-brandizi** [comment]
:-)

We'have to think of this more carefully, according to [their documentation](https://www.nlm.nih.gov/bsd/licensee/elements_descriptions.html), `ArticleDate` doesn't appear in all records. My best guess is that we want to get [`PubMedDate`](https://www.nlm.nih.gov/bsd/licensee/elements_descriptions.html#pubdate) inside `Article/Journal/JournalIssue`. They say this field might not be broken into `year/month/day`, in that case, I can try to see if there is a reasonable number in the `<MedlineDate>`.

Let's agree on this before I put hands on the code again.
