### ISSUE TITLE
UniProt parser: Parse GO class and remove GO file parameter

### ISSUE THREAD

**Issue by KeywanHP** [Rothamsted/ondex-knet-builder#5]
The GO file parameter in the UniProt parser was used to lookup the ontology class P, F or C for each GO annotation in order to create the correct Concept Class and Relation Type. The ontology class information is now included in the UniProt XML itself and therefore the additional GO file is not needed any longer.

I suggest we improve the Parser code to parse F, P or C flags in UniProt XML GO annotations...
```xml
<dbReference type="GO" id="GO:0004497">
    <property type="term" value="F:monooxygenase activity"/>
    <property type="evidence" value="ECO:0000501"/>
    <property type="project" value="UniProtKB-KW"/>
 </dbReference>
```

**Comment by AjitPS** [comment]
Looking into this

**Comment by AjitPS** [comment]
Fixed and implemented in recent commit: https://github.com/Rothamsted/ondex-knet-builder/commit/e0d041e6d2c09b11d06286027925454dc948ac9f thanks @KeywanHP

**Comment by AjitPS** [comment]
can be closed now
