### ISSUE TITLE
Remove GO: prefix from accessions

### ISSUE THREAD

**Issue by KeywanHP** [Rothamsted/ondex-knet-builder#7]
GO accessions need to be modeled in a more consistent way. The new OWL ontology parser creates accessions without GO, TO prefix, I suggest to implement the same behavior in UniProt, GAF and other parsers that create GO annotations.

**Comment by AjitPS** [comment]
@KeywanHP  Is this still a pending issue or has the `owl parser` been modified to match this?

**Comment by marco-brandizi** [comment]
I still haven't changed the owl parser. Going to add an option to decide which prefix to add to the parsed accessions.

**Comment by marco-brandizi** [comment]
I've added the mentioned feature. See examples at https://goo.gl/MoiVMf (look for `property name = "accessionsMappers"`.

You can add a custom prefix to the accession mapper this way:
```<bean id = "idChangedPrefxAccMapper" class = "net.sourceforge.ondex.parser.owl.OWLAccessionsMapper">
					<property name="propertyIri" value="#{ns.iri ( 'oboInOwl:id' )}" />
					<property name="dataSourcePrototype" ref = "goDataSource" />
					<property name="dataSourcePrefix" value = "GO:" />
					<!-- After having removed 'GO' and kept the numerical part od the accession, add 'GenOnt:' -->
					<property name="addedPrefix" value = "GenOnt:" />					
				</bean>	
```

If you set `addedPrefix` to be the same of `dataSourcePrefix` (eg, 'GO:' in both cases), such prefix is used to identify the source value of interest and then retained in the ONDEX accession.

**Comment by AjitPS** [comment]
@KeywanHP I have changed the Uniprot parser to omit the "GO:" prefix and can do the same for the GAF, GenericOBO parser. But then the GO url breaks (without the prefix) so we'll need to change code for that in Ondex config, KnetMaps, KnetMiner Gene View, Evidence View, etc.

**Comment by AjitPS** [comment]
@marco-brandizi  should I leave the other parsers (uniprot, GAF, GenericOBO) with the prefix then?

**Comment by marco-brandizi** [comment]
@AjitPS my impression is it's quicker to use the option in the OWL parser, fewer changes to make. Technically both possibilities are available now.

**Comment by AjitPS** [comment]
Thanks @marco-brandizi , makes sense not to change other parsers then. @Monika-Mistry

**Comment by marco-brandizi** [comment]
@AjitPS, can we close this ticket? Please feel free to do it in case.

**Comment by AjitPS** [comment]
yes, it's fixed now
